apiVersion: v1
kind: ConfigMap
metadata:
  name: pulseops-config
  namespace: pulseops
  labels:
    app.kubernetes.io/name: pulseops
data:
  PORT: "8080"
  DB_PATH: "/data/pulseops.db"
  PROBE_INTERVAL_SECONDS: "30"
  DEFAULT_TARGET_URL: "https://portfolioyusufjaelani.vercel.app"
  DEFAULT_TARGET_NAME: "Yusuf Portfolio"
