apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: pulseops-network-policy
  namespace: pulseops
  labels:
    app.kubernetes.io/name: pulseops
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: pulseops
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Mengizinkan traffic HTTP ke port 8080 untuk web UI, REST API, /healthz, dan /metrics
    - ports:
        - protocol: TCP
          port: 8080
  egress:
    # Izinkan resolusi DNS internal/eksternal untuk probe target domain
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    # Izinkan probe outbound ke target HTTP (80) dan HTTPS (443)
    - ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
