apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pulseops-pvc
  namespace: pulseops
  labels:
    app.kubernetes.io/name: pulseops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
