global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - "alert.rules.yml"
  - "slo.rules.yml"

scrape_configs:
  - job_name: 'pulseops'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['pulseops:8080']
